/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as PulsRouteImport } from './routes/puls'
import { Route as PrichastnostRouteImport } from './routes/prichastnost'
import { Route as NasledieRouteImport } from './routes/nasledie'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as LitsaRouteImport } from './routes/litsa'
import { Route as LetopisRouteImport } from './routes/letopis'
import { Route as KodRouteImport } from './routes/kod'
import { Route as GeografiyaRouteImport } from './routes/geografiya'
import { Route as AzbukaRouteImport } from './routes/azbuka'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PutiIndexRouteImport } from './routes/puti.index'
import { Route as PutiSlugRouteImport } from './routes/puti.$slug'
import { Route as LitsaSlugRouteImport } from './routes/litsa.$slug'
import { Route as Letopis1861RouteImport } from './routes/letopis.1861'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const PulsRoute = PulsRouteImport.update({
  id: '/puls',
  path: '/puls',
  getParentRoute: () => rootRouteImport,
} as any)
const PrichastnostRoute = PrichastnostRouteImport.update({
  id: '/prichastnost',
  path: '/prichastnost',
  getParentRoute: () => rootRouteImport,
} as any)
const NasledieRoute = NasledieRouteImport.update({
  id: '/nasledie',
  path: '/nasledie',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const LitsaRoute = LitsaRouteImport.update({
  id: '/litsa',
  path: '/litsa',
  getParentRoute: () => rootRouteImport,
} as any)
const LetopisRoute = LetopisRouteImport.update({
  id: '/letopis',
  path: '/letopis',
  getParentRoute: () => rootRouteImport,
} as any)
const KodRoute = KodRouteImport.update({
  id: '/kod',
  path: '/kod',
  getParentRoute: () => rootRouteImport,
} as any)
const GeografiyaRoute = GeografiyaRouteImport.update({
  id: '/geografiya',
  path: '/geografiya',
  getParentRoute: () => rootRouteImport,
} as any)
const AzbukaRoute = AzbukaRouteImport.update({
  id: '/azbuka',
  path: '/azbuka',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PutiIndexRoute = PutiIndexRouteImport.update({
  id: '/puti/',
  path: '/puti/',
  getParentRoute: () => rootRouteImport,
} as any)
const PutiSlugRoute = PutiSlugRouteImport.update({
  id: '/puti/$slug',
  path: '/puti/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LitsaSlugRoute = LitsaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LitsaRoute,
} as any)
const Letopis1861Route = Letopis1861RouteImport.update({
  id: '/1861',
  path: '/1861',
  getParentRoute: () => LetopisRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/azbuka': typeof AzbukaRoute
  '/geografiya': typeof GeografiyaRoute
  '/kod': typeof KodRoute
  '/letopis': typeof LetopisRouteWithChildren
  '/litsa': typeof LitsaRouteWithChildren
  '/mission': typeof MissionRoute
  '/nasledie': typeof NasledieRoute
  '/prichastnost': typeof PrichastnostRoute
  '/puls': typeof PulsRoute
  '/test': typeof TestRoute
  '/letopis/1861': typeof Letopis1861Route
  '/litsa/$slug': typeof LitsaSlugRoute
  '/puti/$slug': typeof PutiSlugRoute
  '/puti/': typeof PutiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/azbuka': typeof AzbukaRoute
  '/geografiya': typeof GeografiyaRoute
  '/kod': typeof KodRoute
  '/letopis': typeof LetopisRouteWithChildren
  '/litsa': typeof LitsaRouteWithChildren
  '/mission': typeof MissionRoute
  '/nasledie': typeof NasledieRoute
  '/prichastnost': typeof PrichastnostRoute
  '/puls': typeof PulsRoute
  '/test': typeof TestRoute
  '/letopis/1861': typeof Letopis1861Route
  '/litsa/$slug': typeof LitsaSlugRoute
  '/puti/$slug': typeof PutiSlugRoute
  '/puti': typeof PutiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/azbuka': typeof AzbukaRoute
  '/geografiya': typeof GeografiyaRoute
  '/kod': typeof KodRoute
  '/letopis': typeof LetopisRouteWithChildren
  '/litsa': typeof LitsaRouteWithChildren
  '/mission': typeof MissionRoute
  '/nasledie': typeof NasledieRoute
  '/prichastnost': typeof PrichastnostRoute
  '/puls': typeof PulsRoute
  '/test': typeof TestRoute
  '/letopis/1861': typeof Letopis1861Route
  '/litsa/$slug': typeof LitsaSlugRoute
  '/puti/$slug': typeof PutiSlugRoute
  '/puti/': typeof PutiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/azbuka'
    | '/geografiya'
    | '/kod'
    | '/letopis'
    | '/litsa'
    | '/mission'
    | '/nasledie'
    | '/prichastnost'
    | '/puls'
    | '/test'
    | '/letopis/1861'
    | '/litsa/$slug'
    | '/puti/$slug'
    | '/puti/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/azbuka'
    | '/geografiya'
    | '/kod'
    | '/letopis'
    | '/litsa'
    | '/mission'
    | '/nasledie'
    | '/prichastnost'
    | '/puls'
    | '/test'
    | '/letopis/1861'
    | '/litsa/$slug'
    | '/puti/$slug'
    | '/puti'
  id:
    | '__root__'
    | '/'
    | '/azbuka'
    | '/geografiya'
    | '/kod'
    | '/letopis'
    | '/litsa'
    | '/mission'
    | '/nasledie'
    | '/prichastnost'
    | '/puls'
    | '/test'
    | '/letopis/1861'
    | '/litsa/$slug'
    | '/puti/$slug'
    | '/puti/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AzbukaRoute: typeof AzbukaRoute
  GeografiyaRoute: typeof GeografiyaRoute
  KodRoute: typeof KodRoute
  LetopisRoute: typeof LetopisRouteWithChildren
  LitsaRoute: typeof LitsaRouteWithChildren
  MissionRoute: typeof MissionRoute
  NasledieRoute: typeof NasledieRoute
  PrichastnostRoute: typeof PrichastnostRoute
  PulsRoute: typeof PulsRoute
  TestRoute: typeof TestRoute
  PutiSlugRoute: typeof PutiSlugRoute
  PutiIndexRoute: typeof PutiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puls': {
      id: '/puls'
      path: '/puls'
      fullPath: '/puls'
      preLoaderRoute: typeof PulsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prichastnost': {
      id: '/prichastnost'
      path: '/prichastnost'
      fullPath: '/prichastnost'
      preLoaderRoute: typeof PrichastnostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nasledie': {
      id: '/nasledie'
      path: '/nasledie'
      fullPath: '/nasledie'
      preLoaderRoute: typeof NasledieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/litsa': {
      id: '/litsa'
      path: '/litsa'
      fullPath: '/litsa'
      preLoaderRoute: typeof LitsaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letopis': {
      id: '/letopis'
      path: '/letopis'
      fullPath: '/letopis'
      preLoaderRoute: typeof LetopisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kod': {
      id: '/kod'
      path: '/kod'
      fullPath: '/kod'
      preLoaderRoute: typeof KodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geografiya': {
      id: '/geografiya'
      path: '/geografiya'
      fullPath: '/geografiya'
      preLoaderRoute: typeof GeografiyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/azbuka': {
      id: '/azbuka'
      path: '/azbuka'
      fullPath: '/azbuka'
      preLoaderRoute: typeof AzbukaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puti/': {
      id: '/puti/'
      path: '/puti'
      fullPath: '/puti/'
      preLoaderRoute: typeof PutiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puti/$slug': {
      id: '/puti/$slug'
      path: '/puti/$slug'
      fullPath: '/puti/$slug'
      preLoaderRoute: typeof PutiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/litsa/$slug': {
      id: '/litsa/$slug'
      path: '/$slug'
      fullPath: '/litsa/$slug'
      preLoaderRoute: typeof LitsaSlugRouteImport
      parentRoute: typeof LitsaRoute
    }
    '/letopis/1861': {
      id: '/letopis/1861'
      path: '/1861'
      fullPath: '/letopis/1861'
      preLoaderRoute: typeof Letopis1861RouteImport
      parentRoute: typeof LetopisRoute
    }
  }
}

interface LetopisRouteChildren {
  Letopis1861Route: typeof Letopis1861Route
}

const LetopisRouteChildren: LetopisRouteChildren = {
  Letopis1861Route: Letopis1861Route,
}

const LetopisRouteWithChildren =
  LetopisRoute._addFileChildren(LetopisRouteChildren)

interface LitsaRouteChildren {
  LitsaSlugRoute: typeof LitsaSlugRoute
}

const LitsaRouteChildren: LitsaRouteChildren = {
  LitsaSlugRoute: LitsaSlugRoute,
}

const LitsaRouteWithChildren = LitsaRoute._addFileChildren(LitsaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AzbukaRoute: AzbukaRoute,
  GeografiyaRoute: GeografiyaRoute,
  KodRoute: KodRoute,
  LetopisRoute: LetopisRouteWithChildren,
  LitsaRoute: LitsaRouteWithChildren,
  MissionRoute: MissionRoute,
  NasledieRoute: NasledieRoute,
  PrichastnostRoute: PrichastnostRoute,
  PulsRoute: PulsRoute,
  TestRoute: TestRoute,
  PutiSlugRoute: PutiSlugRoute,
  PutiIndexRoute: PutiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
